language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - cd ..
  - django-admin.py startproject --template=./django-aws-template --extension=py,md,html,env my_proj
  - cd my_proj/server
  - cp config/settings/local.sample.env config/settings/.local.env
  - python manage.py migrate
script:
  - python manage.py test profiles