version: '3.7'

x-server-env: &server-env
  DJANGO_SETTINGS_MODULE: config.settings.docker
  DJANGO_ENV_FILE: .docker.env
  DJANGO_SECRET_KEY: stage-dummy-key1
  SECRET_KEY: stage-dummy-key1
  DATABASE_URL: postgres://postgres:postgres@db/postgres
  RDS_DB_NAME: ${RDS_DB_NAME:-postgres}
  RDS_USERNAME: ${RDS_USERNAME:-postgres}
  RDS_PASSWORD: ${RDS_PASSWORD:-pass.123}
  RDS_HOSTNAME: ${RDS_HOSTNAME:-db}
  RDS_PORT: 5432

services:

  db:
    restart: always
    image: postgres:11.8
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
      - /data

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/www/static
    depends_on:
      - web

  web:
    build:
      context: ./server/
    volumes:
      - ./logs:/var/app/logs
      - ./server:/var/app
      - ./staticfiles:/www/static
    ports:
      - "8000:8000"
    command: /var/app/runserver.sh
    depends_on:
      - db
    environment:
      <<: *server-env

  init:
    build:
      context: ./server/
    volumes:
      - ./logs:/var/app/logs
      - ./server:/var/app
      - ./staticfiles:/www/static
    command: ["sh", "-c", "/var/app/server-init.sh"]
    restart: "no"
    depends_on:
      - db
    environment:
      <<: *server-env
